# Alacritty Configuration File
# See https://alacritty.org/config-alacritty.html for details.
general.import = ['./catppuccin-macchiato.toml']

# Window settings
[window]
# Start maximized
startup_mode = "Windowed"
# Set window padding (in pixels)
padding = { x = 10, y = 10 }
# Set window opacity (1.0 = fully opaque, 0.0 = fully transparent)
opacity = 1.0
decorations = "Buttonless"

# Font settings
[font]
size = 18.0
# Normal font face
[font.normal]
family = "Fira Code"

# Bold font face (optional)
[font.bold]
family = "Fira Code"

# Italic font face (optional)
[font.italic]
family = "Fira Code"

# Bold italic font face (optional)
[font.bold_italic]
family = "Fira Code"

# Scrolling behavior
[scrolling]
# Scrollback buffer lines
history = 10000
# Scroll multiplier for mouse wheel
multiplier = 3


